<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms & Conditions | Truck Wale</title>
    
    <link rel="icon" href="assets/img/truckwale-logo-favicon.png" type="image/gif" sizes="32x32">
    <style>
        html, body {
            margin: 0 auto;
            font-family: 'Roboto', sans-serif;
            height: 100%;
            background: #f4f6f9;
            font-weight: 100;
            -webkit-user-select: none;
                -moz-user-select: none;
                -ms-user-select: none;
                    user-select: none;
            }

            main {
            height: 100%;
            display: -webkit-box;
            display: flex;
            margin: 0 20px;
            text-align: center;
            -webkit-box-orient: vertical;
            -webkit-box-direction: normal;
                    flex-direction: column;
            -webkit-box-align: center;
                    align-items: center;
            -webkit-box-pack: center;
                    justify-content: center;
            }
            main h1 {
            font-size: 3em;
            font-weight: 100;
            color: #0a0a0a;
            margin: 0;
            }
            main h2 {
            font-size: 1.5em;
            font-weight: 100;
            margin-bottom: 0;
            }
            main h3 {
            font-size: 1.5em;
            font-weight: 100;
            margin-top: 0;
            }
            main a {
            font-size: 1.5em;
            font-weight: 300;
            color: #0a0a0a;
            text-decoration: none;
            }

            footer {
            position: absolute;
            bottom: 0;
            margin: 10px;
            font-weight: 300;
            }
    </style>
</head>
<body>
    
<div class="container" style="color: black; margin: 100px;">

<div style="width: 100%; text-align: center;"><img src="assets/img/truck-logo-sm.png" style="width: 100px; height: 100px; margin-bottom: 50px;" alt=""></div>
            

          <h2 style="text-align: justify;">Terms & Conditions</h2>

<p>TruckWale | DWARKADHISH INTERNET SERVICES PRIVATE LIMITED | TruckWale</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>This Site/ Application/ Services is/are operated /provided by DWARKADHISH INTERNET SERVICES PRIVATE LIMITED.</p>
<p>&nbsp;</p>
<p>These terms and conditions (&ldquo;User Terms&rdquo;) apply to Your visit to and use, of the Site whether through a computer or a mobile phone, the Service and the Application, as well as to all information, recommendations and or services provided to You on or through the Site, the Service and the Application. This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. By clicking on the &ldquo;I ACCEPT&rdquo; button, You are consenting to be bound by these User Terms. PLEASE ENSURE THAT YOU READ AND UNDERSTAND ALL THESE USER TERMS BEFORE YOU USE THE SITE. If You do not accept any of the User Terms, then please do not use the Site or avail of any of the services being provided therein. YOUR AGREEMENT TO THESE USER TERMS SHALL OPERATE AS A BINDING AGREEMENT BETWEEN YOU AND TRUCKWALE IN RESPECT OF THE USE AND SERVICES OF THE SITE.</p>
<p>&nbsp;</p>
<p>Your acceptance of the User Terms shall be deemed to include your acceptance of the privacy policy available at https://www.truckwale.co.in/info/faqs#privacyPolicy. By accepting these User Terms, you also allow TruckWale to send you promotional emails and SMS alerts from time to time.</p>
<p>&nbsp;</p>
<p>IT IS HEREBY EXPRESSLY CLARIFIED THAT THESE USER TERMS WILL NOT APPLY TO CORPORATE ENTITIES THAT ARE GOVERNED BY THE TruckWale CORPORATE TERMS OF USE. HOWEVER, ALL AUTHORISED USERS TAKING &lsquo;TruckWale CORPORATE RIDES&rsquo; I.E., FOR CUSTOMERS WHO ARE AVAILING RIDES UNDER THE DIRECT ARRANGEMENTS BETWEEN CORPORATE ENTITIES AND TruckWale SHALL ALSO BE GOVERNED BY THESE USER TERMS.</p>
<p>&nbsp;</p>
<ol>
<li>DEFINITIONS</li>
</ol>
<p>&nbsp;</p>
<p>All of the defined and capitalised terms in these User Terms will have the meaning assigned to them here below:</p>
<p>&nbsp;</p>
<p>(i) &ldquo;Account&rdquo; shall mean the account created by the Customer on the Application for availing the Services provided by TruckWale.</p>
<p>&nbsp;</p>
<p>(ii) &ldquo;Additional Fee&rdquo; shall mean any toll duty, inter-state taxes, etc. as may not be included in the Fare or not already paid as a part of the Total Ride Fee but payable to any third party/government authorities for undertaking the ride under Applicable Law.</p>
<p>&nbsp;</p>
<p>(iii) &ldquo;Applicable Laws&rdquo; shall mean and include all applicable statutes, enactments, acts of legislature or parliament, laws, ordinances, rules, by-laws, regulations, notifications, guidelines, policies, directions, directives and orders of any governmental authority, tribunal, or a court of India.</p>
<p>&nbsp;</p>
<p>(iv) &ldquo;Application&rdquo; shall mean the mobile application &ldquo;TruckWale&rdquo; updated by TruckWale from time to time.</p>
<p>&nbsp;</p>
<p>(v) &ldquo;Convenience Fee&rdquo;/&rdquo; Access Fee&rdquo; shall mean the fee payable by the Customer to TruckWale for the Service i.e., for availing the technology services offered by TruckWale, door-to-door service, Wi-Fi access, customer support and cashless payment options. A convenience fee shall be chargeable on every booking made through the Site. The Convenience Fee shall be exclusive of all applicable taxes on the Convenience Fee if any.</p>
<p>&nbsp;</p>
<p>(vi) &ldquo;Cancellation Fee&rdquo; shall mean the Fare and Convenience Fee payable towards cancellation of a ride by a Customer in terms of Clause 7 of these User Terms and the Cancellation Terms and Conditions available at https://www.truckwale.co.in/info/faqs#Cancellations. The Cancellation Fee shall be exclusive of all applicable taxes on the Cancellation Fee if any.</p>
<p>&nbsp;</p>
<p>(vii) &ldquo;City of Operation&rdquo; shall mean a city in which the Customers and TPSPs avail and render the transportation services, respectively. For clarity, the services rendered by the TPSPs and availed by the Customers shall be in the same city.</p>
<p>&nbsp;</p>
<p>(viii) &ldquo;Customer/ You&rdquo; means a person who has an Account on the Application.</p>
<p>&nbsp;</p>
<p>(ix) &ldquo;Driver&rdquo; shall mean and include such individuals as may be evaluated, appointed and trained by an operator associated with us to provide the transportation services on its behalf and persons who are registered with TruckWale and own the Vehicles and who have necessary city taxi permits and other applicable transport vehicle permits and licences to provide transportation services within the City of Operation.</p>
<p>&nbsp;</p>
<p>(x) &ldquo;E-Wallet&rdquo; shall mean a pre-paid instrument, which can be used to make payments.</p>
<p>&nbsp;</p>
<p>(xi) &ldquo;Fare&rdquo; shall mean such amount in Indian Rupees, which is reflected on the Application, as the fare payable for the specific Ride performed by a Driver. The Fare shall be exclusive of all applicable taxes on the Fare if any. In relation to Auto (a motor cab), the Fare shall be as prescribed by law and/or as stipulated by relevant authorities.</p>
<p>&nbsp;</p>
<p>(xii) &ldquo;Force Majeure Event&rdquo; shall mean any event arising due to any cause beyond the reasonable control of TruckWale.</p>
<p>&nbsp;</p>
<p>(xiii) &ldquo;TruckWale&rdquo; or &ldquo;us&rdquo; or &ldquo;we&rdquo; or &ldquo;our&rdquo; shall mean DWARKADHISH INTERNET SERVICES PRIVATE LIMITED, which expression shall, unless it is repugnant to the context or meaning thereof, be deemed to mean and include all its successors, affiliates and permitted assigns.</p>
<p>&nbsp;</p>
<p>(xiv) &ldquo;Registration Data&rdquo; shall mean and may include the present, valid, true and accurate name, email ID, phone number and such other information as may be required by TruckWale from the Customer from time to time for registration on the Application.</p>
<p>&nbsp;</p>
<p>(xv) &ldquo;Ride&rdquo; shall mean the travel in the Vehicle by the Customer facilitated through the Site.</p>
<p>&nbsp;</p>
<p>(xvi) &ldquo;Service(s)&rdquo; means the facilitation of transportation service by TruckWale through the Application or via a telephone request at the call centre of TruckWale, or booking on the Site, within the City of Operation, as elaborated in Clause 4.</p>
<p>&nbsp;</p>
<p>(xvii) &ldquo;Site&rdquo; shall mean the Application and the website https://www.truckwale.co.in/ operated by TruckWale or any other software that enables the use of the Application or such other URL as may be specifically provided by TruckWale.</p>
<p>&nbsp;</p>
<p>(xviii) &ldquo;Substitute Vehicle&rdquo; shall mean another vehicle arranged for transporting the Customers to his/her destination, in the event of a vehicle breakdown.</p>
<p>&nbsp;</p>
<p>(xix) &ldquo;Total Ride Fee&rdquo; shall mean and include the Fare, the Convenience Fee or Access Fee, the Cancellation Fee and Additional Fee and taxes as may be applicable from time to time.</p>
<p>&nbsp;</p>
<p>(xx) &ldquo;T&amp;Cs&rdquo; and &ldquo;User Terms&rdquo; shall mean these Customer terms and conditions.</p>
<p>&nbsp;</p>
<p>(xxi) &ldquo;TPSP&rdquo; shall mean a Driver and/or an operator associated with us offering the service of transporting Customers within the City of Operation as requested by the Customer on the Application.</p>
<p>&nbsp;</p>
<p>(xxii) &ldquo;Vehicle&rdquo; shall mean a motor cab as defined under the Motor Vehicles Act,1988.</p>
<p>&nbsp;</p>
<ol start="2">
<li>ELIGIBILITY</li>
</ol>
<p>&nbsp;</p>
<p>You will be &ldquo;Eligible&rdquo; to use the services only when You fulfil all of the following conditions: (i) You have attained at least 18 (eighteen) years of age. (ii) You are competent to enter into a contract under the Applicable Laws.</p>
<p>&nbsp;</p>
<p>If You reside in a jurisdiction that restricts the use of the Service because of age or restricts the ability to enter into contracts such as this User Terms due to age, You must abide by such age limits.</p>
<p>&nbsp;</p>
<ol start="3">
<li>REGISTRATION AND ACCOUNT</li>
</ol>
<p>&nbsp;</p>
<p>3.1 You understand and acknowledge that You can register on the site only after complying with the requirements of this Clause 3 and by Entering Your Registration Data.</p>
<p>&nbsp;</p>
<p>3.2 You shall ensure that the Registration Data provided by You is accurate, complete, current, valid and true and is updated from time to time. We shall bear no liability for false, incomplete, old or incorrect Registration Data provided by You.</p>
<p>&nbsp;</p>
<p>3.3 You are solely responsible for maintaining the confidentiality of Your Registration Data and will be liable for all activities and transactions that occur through Your Account, whether initiated by You or any third party. Your Account cannot be transferred, assigned or sold to a third party. We shall not be liable for any loss that You may incur as a result of someone else using Your password or Account, either with or without Your knowledge.</p>
<p>&nbsp;</p>
<p>3.4 We reserve the right to suspend or terminate Your Account with immediate effect and for an indefinite period, if We have a reason to believe that the Registration Data or any other data provided by You is incorrect or false, or that the security of Your Account has been compromised in any way, or for any other reason We may find just or equitable.</p>
<p>&nbsp;</p>
<p>3.5 Except for the Registration Data or any other data submitted by You during the use of any other service offered through Site (&ldquo;Permitted Information&rdquo;), TruckWale does not want You to, and You should not, send any confidential or proprietary information to TruckWale on the Site or otherwise, unless otherwise is required by Applicable Laws. In accepting these User Terms, You agree that any information or materials that You or individuals acting on Your behalf provide to TruckWale other than the Permitted Information will not be considered confidential or proprietary.</p>
<p>&nbsp;</p>
<p>3.6 It is Your responsibility to check to ensure that You download the correct application for Your device. We are not liable if you do not have a compatible mobile device or if you download the wrong version of the Application for Your mobile device. We reserve the right to terminate the Service and the use of the Application should you be using the Service or Application with an incompatible or unauthorised device.</p>
<p>&nbsp;</p>
<p>3.7 We allow You to open only one Account in association with the Registration Data provided by You. In case of any unauthorised use of Your Account, please immediately reach Us at support@truckwale.co.in. 3.8 In case, You are unable to access Your Account, please inform Us at support@truckwale.co.in and make a written request for blocking Your Account. We will not be liable for any unauthorised transactions made through Your Account prior to the expiry of 72 (seventy-two) hours after You have made a request in writing for blocking Your Account, and shall not have any liability in case of Force Majeure Event.</p>
<p>&nbsp;</p>
<ol start="4">
<li>SERVICES</li>
</ol>
<p>&nbsp;</p>
<p>4.1. The Site permits you to avail of the transportation services offered by TPSPs. The Service allows you to send a request through TruckWale to a Driver on the TruckWale network. The Driver has sole and complete discretion to accept or reject each request for Service. If the driver accepts a request, TruckWale notifies You and provides information regarding the Driver - including Driver Name, Vehicle licence number, telephone contact details of the Driver and such other details as TruckWale may determine.</p>
<p>&nbsp;</p>
<p>4.2. TruckWale shall procure reasonable efforts to bring You into contact with a Driver, subject to the availability of a Driver in or around Your location at the moment of Your request for such services.</p>
<p>&nbsp;</p>
<p>4.3. By using the Application or the Service, You further agree that: (i) You will only use the Service or download the Application for Your sole, personal use and will not resell or assign it to a third party; (ii) You will not use an account that is subject to any rights of a person other than You without appropriate authorisation; (iii) You will not use the Service or Site for unlawful purposes; (iv) You will not try to harm the Service, site or our network in any way whatsoever; (v) You will provide TruckWale with such information and documents, which TruckWale may reasonably request; (vi) You will only use an authorised network to avail the Service; (vii) You are aware that when requesting Services, whether by message, via Site or calling the call centre of TruckWale, standard messaging charges, data charges, voice charges, as applicable, of Your and Our phone network service providers, will apply; (viii) You will comply with all Applicable Law from Your country of domicile and residence and the country, state and/or city in which You are present while using the Site or Service; and (ix) You are aware of and shall comply with the Information Technology Act, 2000 and the rules, regulations and guidelines notified thereunder.</p>
<p>&nbsp;</p>
<p>4.4. TruckWale reserves the right to immediately terminate the Service and the use of the Application in the event of non-compliance with any of the above requirements. Further, TruckWale will store the information provided by You or record your calls for contacting You for all Service related matters. You shall promptly inform TruckWale of any change in the information provided by You.</p>
<p>&nbsp;</p>
<p>4.5. TruckWale or an authorised representative of TruckWale, shall provide information regarding services, discounts and promotions provided by TruckWale to You by way of an SMS or email to Your registered mobile number/registered email ID. You also have the option to discontinue receiving such information at any point in time. To discontinue receiving such information, You may at any point of time visit the specific link provided in the Site to discontinue the same.</p>
<p>&nbsp;</p>
<p>4.6. TruckWale WILL BE ENTITLED TO PROCESS AND TRANSFER YOUR INFORMATION AS AND WHEN IT DEEMS FIT AND IT MAY STORE OR TRANSFER YOUR INFORMATION IN A SERVER OUTSIDE INDIA OR THE COUNTRY WHERE YOU ARE LOCATED IN ORDER TO PERFORM TruckWale&rsquo;S OBLIGATIONS UNDER THESE CUSTOMER T&amp;C.</p>
<p>&nbsp;</p>
<p>4.7. You agree to grant TruckWale a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights You have in your information, in any media now known or not currently known, with respect to Your information. YOU AGREE AND PERMIT TruckWale TO SHARE YOUR INFORMATION AND/OR PERMITTED INFORMATION, WITH THIRD PARTIES.</p>
<p>&nbsp;</p>
<p>4.8. You agree and permit TruckWale to share any information provided by You with third parties in order to facilitate the provision of certain value-added services offered by such third parties to You and/or to provide certain value-added services to You by TruckWale. You hereby expressly consent to receive communications from TruckWale/ third parties offering value-added services to You through Your registered phone number and/or e-mail ID and/or the Site. You agree that you will not hold TruckWale responsible for any such communications received from third parties, nor will any such communication amount to spam, unsolicited communication or a violation of Your registration on the national do not call registry.</p>
<p>&nbsp;</p>
<p>4.9. TruckWale will be entitled to enter into any tie-up in terms of joint-venture or otherwise, with any other institution engaged in the business of providing services analogous and/or similar to those herein contained. In such case, depending upon the modality and the mechanism as may be devised, you will be provided with the services by TruckWale jointly and/or severally with the parties in a joint venture. You hereby give your irrevocable consent and permission to such a tie-up. In the event of such a tie-up, the terms and conditions herein contained will, mutatis mutandis, become applicable in respect of such tie-up arrangement as well.</p>
<p>&nbsp;</p>
<p>4.10. In the event TruckWale provides You with any device as a part of the Services, including but not limited to TruckWale Play (&ldquo;TruckWale Device&rdquo;), You shall comply with the following. &lsquo;TruckWale Play&rsquo; means a connected car platform using multiple devices in-car and cloud technology platform owned and operated by TruckWale, which endeavours to provide an interactive experience to You &ndash; (i) You shall not tamper, pilfer or misuse the TruckWale Device(s) or allow, induce or assist a third party to indulge in such activity. (ii) You shall not transcribe, distribute, download, store, duplicate and reproduce the content forming part of the TruckWale Device(s) (&ldquo;Content&rdquo;), in whole or in part, through any medium including, but not limited to, tape, disc, hard disk, computer system, or other electronic recording or transmission device. (iii) You shall not (i) license, sub-license, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party, in any way, the TruckWale Device(s) and/or any Content; (ii) modify or make derivative works from the Content; (iii) create Internet &ldquo;links&rdquo; to the content or &ldquo;frame&rdquo; or &ldquo;mirror&rdquo; any Content on any other server or wireless or internet-based device; (iv) reverse engineer or access the TruckWale Device(s) and/or Content in order to (a) design or build a competitive product or service, (b) design or build a product using similar ideas, features, functions or graphics of the TruckWale Device(s) and/or Content, or (c) copy any ideas, features, functions or graphics of the TruckWale Device(s) and/or Content, or (v) launch an automated program or script, including, but not limited to, web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per second, or unduly burdens or hinders the operation and/or performance of the TruckWale Device and/or Content (iv) You shall not use the TruckWale Device(s) for any illegal or unlawful purposes including but not limited to playing/watching pornographic content on the TruckWale Device and shall use the TruckWale Device(s) solely for purposes determined by TruckWale and strictly in accordance with these User Terms. You shall solely be responsible and liable for any violations of law committed by You and misuse of the TruckWale Device(s), if any, with the TruckWale Device(s). (v) You shall ensure that the TruckWale Device(s) is maintained in your possession in a proper manner. TruckWale may, at its sole discretion, charge such amounts from You as may be determined by TruckWale for use of the TruckWale Device(s) by You. (vi) In the event the TruckWale Device(s) is not functioning properly or if there is any technical or safety issue in relation to the TruckWale Device(s), You shall immediately inform the Driver about any such issue. (vii) You shall use the TruckWale Device(s) with due care and caution and not do anything or permit anything to be done that may cause damage to the TruckWale Device(s). If the TruckWale Device(s) is damaged and is not repairable due to any act of You, You shall pay amounts to TruckWale, as may be determined by TruckWale. If You fail or are unable to pay the amounts determined by TruckWale, TruckWale shall be entitled to suspend/terminate Your Account with TruckWale without prejudice to TruckWale&rsquo;s rights under these User Terms and under Applicable Laws.</p>
<p>&nbsp;</p>
<p>4.11. In the event of a breakdown of the Vehicle, which is beyond repair, before completion of the Ride, TruckWale on the best effort basis and at its sole discretion may arrange for a Substitute Vehicle for completion of Your Ride to Your destination. However, the arrangement of a Substitute Vehicle shall be subject to its availability.</p>
<p>&nbsp;</p>
<p>4.12. You acknowledge and agree that the Substitute Vehicle may not be necessary of the same type as the original Vehicle booked by You from the Site.</p>
<p>&nbsp;</p>
<p>4.13. TruckWale bears no responsibility and liability for delays and losses suffered by You or caused to You as a consequence of the breakdown of the Vehicle or the Substitute Vehicle.</p>
<p>&nbsp;</p>
<ol start="5">
<li>CONFIRMATION OF BOOKING</li>
</ol>
<p>&nbsp;</p>
<p>5.1. TruckWale shall, upon receiving the booking request from You in the manner set out above, proceed to confirm or decline the booking based on the availability of Vehicles at the pickup time, which shall be informed to You vide an SMS or email. In the event the booking is confirmed, You shall check the booking details including but not limited to pick up time and pick up place, and if there is incorrect detail, the same needs to be informed to us immediately by calling our call centre.</p>
<p>&nbsp;</p>
<p>5.2. You shall bear the consequences and damages for any delay that may be caused to You due to Your failure to check the confirmation SMS or email or failure to inform TruckWale of the incorrect details immediately.</p>
<p>&nbsp;</p>
<p>5.3. Certain selective customers will be eligible to avail of the Service under a &lsquo;Guest Booking&rsquo; feature, provided by TruckWale. Such customers will also be bound by the terms and conditions set out herein.</p>
<p>&nbsp;</p>
<ol start="6">
<li>PAYMENT</li>
</ol>
<p>&nbsp;</p>
<p>6.1. TruckWale shall charge Convenience Fee or Access Fee for the Service which shall be determined and amended at the sole and absolute discretion of TruckWale. The Convenience Fee or Access Fee shall be payable by you to TruckWale and shall be informed to you before you begin your ride.</p>
<p>&nbsp;</p>
<p>6.2. In relation to TruckWale Autos plying within the City of Operation the Convenience Fee or Access Fee shall not exceed an amount of Rs 75 at any time.</p>
<p>&nbsp;</p>
<p>6.3. TPSP shall charge Fare to You for the Ride offered to You by the TPSP.</p>
<p>&nbsp;</p>
<p>6.4. You shall be required to pay such an Additional Fee, which will form part of the receipt of the Total Ride Fee.</p>
<p>&nbsp;</p>
<p>6.5. You shall be required to pay such a Cancellation Fee in terms of Clause 7, which will form part of the receipt of the Total Ride Fee. 6.6. In addition to the Total Ride Fee, You may be required to pay such other charges incurred by you during the Ride in cash i.e. Additional Fee, which are not included in the receipt of the Total Ride Fee.</p>
<p>&nbsp;</p>
<p>6.7. The Total Ride Fee will be collected by the Driver or TruckWale from You at the end of the Ride, as set out in Clause 6.7 below.</p>
<p>&nbsp;</p>
<p>6.8. TruckWale shall provide a receipt of the Total Ride Fee payable by You at the end of the Ride, however, separate invoices raised by the TPSPs for the Fare and Additional Fee, and the Convenience Fee or Access Fee raised by TruckWale shall be provided to You on request. You may raise a request for a copy of the invoices from our Support page.</p>
<p>&nbsp;</p>
<p>6.9. All applicable taxes in respect of the Fare, Convenience Fee, Additional Fee, Cancellation Fee shall be borne and payable by You to the TPSPs or TruckWale, as the case may be.</p>
<p>&nbsp;</p>
<p>6.10. You shall choose to pay for the Service Fee by either of the following four methods: (i) Cash payment: Cash payment towards the Total Ride Fee after the completion of Ride can be made to the Driver. (ii) E-Wallet payment: TruckWale offers you the facility of making an online payment through an E-Wallet powered by a third party payment processor (&ldquo;Payment Processor&rdquo;). E-Wallet money will not be applicable on bookings made through the phone or while the user is not logged into his/her Account on the Site. The processing of payments, in connection with your use of the E-Wallet, will be subject to the terms, conditions, and privacy policies of the Payment Processor that TruckWale engages for the purpose. TruckWale will not be responsible for any errors by the Payment Processor in any manner. Further, even in cases of E-Wallet payments, all Additional Fee (defined below) shall have to be paid by You in cash, to the authority or person concerned or if already paid by the Driver, to the Driver. When You choose to make an E-Wallet payment, TruckWale shall collect the Fare on behalf of the TPSP who will be responsible for providing the transportation services. (iii) TruckWale Credit Payment: Payment for the Total Ride Fee can be made to TruckWale on credit subject to the terms provided at https://s3-ap-southeast-1.amazonaws.com/truckwale-prod-website/TERMS+AND+CONDITIONS_TruckWale+CREDIT.pdf Further, even in cases of TruckWale Credit payments, all Additional Fee shall have to be paid by You in cash, to the authority or person concerned or if already paid by the Driver, to the Driver. When You choose to make an TruckWale Credit payment, TruckWale shall collect the Fare on behalf of the TPSP who will be responsible for providing the transportation services. (iv) Credit Card/ Debit Card/ Net Banking Payment: Total Ride Fee shall be effected using the services of an entity providing payment gateway/processor services (&ldquo;PG&rdquo;), authorised by TruckWale. Such PG may either be TruckWale or any of its affiliates or partners or unrelated third parties. You agree and undertake to share relevant payment details including credit/debit card details (Card Details) with the PG for the successful completion of payment towards Total Ride Fee to TruckWale and authorise the PG to complete such transactions. In this respect, it is clarified that all PGs whose services are utilised for the purposes of the Site and/or Application and/or Services shall be PCI-DSS (Payment Card Industry &ndash; Data Security Standard) compliant. Your authorisation permits the PG to debit or credit the bank account associated with your payment details. Your authorisation further permits the PG to use Your Card Details for the processing of transactions initiated by You at any of TruckWale&rsquo;s affiliates. Your authorisation will remain in effect as long as You maintain an Account with Us. In the event, You delete Your Card Details with the PG or if You delete Your Account, the PG will not process any further transactions initiated by You at the Site or Application and at the sites of any of TruckWale&rsquo;s affiliates. Your authorization under this clause is subject to any other terms and conditions of the PG.</p>
<p>&nbsp;</p>
<p>6.11. Any payment-related issue, except when such issue is due to an error or fault in the Site, shall be resolved between You and the Payment Processor. TruckWale shall not be responsible for any unauthorized use of Your E-Wallet during or after availing the Services on the Site.</p>
<p>&nbsp;</p>
<ol start="7">
<li>CANCELLATION POLICY</li>
</ol>
<p>&nbsp;</p>
<p>7.1. You agree and acknowledge that You may cancel Your request for a Vehicle from a Driver at any point of time subject to a Cancellation Fee as explained below: In Micro/Mini/Prime/Sedan/SUV/Luxury/Rental categories, Cancellation Fee will be charged</p>
<p>&nbsp;</p>
<ul>
<li>If you cancel after 5 minutes after the cab is allotted or &bull; If a driver cancels after waiting at Your location for more than 10 minutes &bull; Notwithstanding the foregoing, if the Driver is delayed by more than five (5) minutes to pick You, You will not be charged any Cancellation Fee.</li>
</ul>
<p>&nbsp;</p>
<p>7.2. You shall be notified of the applicable Cancellation Fee in advance whenever you attempt to cancel a booking/service request. The notification shall be on the Application and/or the Site.</p>
<p>&nbsp;</p>
<p>7.3. TruckWale shall provide a receipt of the Cancellation Fee, if any, payable by You for every cancellation in terms of the table above for such cancellations, however, separate invoices raised by the TPSPs for the Cancellation Fee, and TruckWale for the Convenience Fee on cancellations shall be provided to You on request. You may raise a request for a copy of the invoices from the Support page.</p>
<p>&nbsp;</p>
<p>7.4. The Cancellation Fee shall be payable by You at the completion of Your subsequent Ride.</p>
<p>&nbsp;</p>
<p>7.5. The mode of payment of the Cancellation Fee shall be in terms of Clause 7 of these User Terms.</p>
<p>&nbsp;</p>
<p>7.6. This Clause 7 shall not apply to corporate rides availed pursuant to the terms and conditions.</p>
<p>&nbsp;</p>
<ol start="8">
<li>USER VIOLATION OF USER TERMS</li>
</ol>
<p>&nbsp;</p>
<p>8.1. You shall not smoke and drink in the Vehicles or misbehave with the Driver or distract the Driver or act in violation of Applicable Law. In the event You are found to be involved in the activities set out above, You shall be liable to pay a fine to us, and we shall also have the right to terminate the Ride. In the event you fail to pay the fine after the completion of the Ride, we may, at our discretion, take such steps as may be available to us under Applicable Law. You shall also be blacklisted as a result of non-payment of the fine or misbehaving as the case may be, and in such event, Your Account may be terminated by.</p>
<p>&nbsp;</p>
<ol start="9">
<li>CUSTOMER RELATIONSHIP MANAGEMENT 9.1. All issues, opinions, suggestions, questions and feedback while availing our Services shall be communicated to us through the email address mentioned in Clause 22.2. In case of a Ride booked on our Application, You shall be required to rate the Ride after its termination. You agree to be fair, accurate and non-disparaging while leaving comment, feedbacks, testimonials or reviews on or about the Rides or Services.</li>
</ol>
<p>&nbsp;</p>
<p>9.2. Reporting of any issue needs to be within 7 (seven) days of the happening of the issue, failing which, such issue will not be addressed.</p>
<p>&nbsp;</p>
<p>9.3. Any issue reported on channels other than the above may be addressed by TruckWale only on a best-effort basis. TruckWale takes no liability for the inability to get back on other channels.</p>
<p>&nbsp;</p>
<p>9.4. TruckWale shall endeavour to respond to Your issues within 2 (two) working days of Your reporting the same and endeavour to resolve it at the earliest possible. It is hereby clarified that issues are resolved on a severity basis, and certain may be resolved earlier than the other. However, TruckWale shall not be liable for any damages or losses in the event you are not satisfied with any such resolution.</p>
<p>&nbsp;</p>
<ol start="10">
<li>EMERGENCY SERVICES TO CUSTOMER</li>
</ol>
<p>&nbsp;</p>
<p>10.1 By accepting these User Terms and on pressing the SOS button on the TruckWale App, You consent to TruckWale using its best endeavours to provide You with assistance during a safety incident, emergencies or distress, as per TruckWale&rsquo;s internal policies on emergency response. TruckWale may undertake remedial action(s), including, but not limited to the following:</p>
<p>&nbsp;</p>
<p>10.1.1 When you press the SOS button and report a safety incident, the TruckWale representative may escalate the incident internally or liaise with any third-party security service providers to assist you and/or deploy response teams to your location.</p>
<p>&nbsp;</p>
<p>10.1.2 TruckWale may inform any government authorities, such as the concerned police station, about the incident and seek their assistance; TruckWale may also provide such authority(ies) with your personal information including but not limited to your exact GPS location, your registered email ID and mobile number to enable them to take appropriate steps to assist you.</p>
<p>&nbsp;</p>
<p>10.1.3 TruckWale may engage third-party security providers to assist you and TruckWale in addressing the incident. For this purpose, TruckWale may share your personal information, including but not limited to, your exact GPS location, your registered email ID and mobile number with third</p>
<p>&nbsp;</p>
<p>parties such as a security services provider, to enable them to take appropriate steps to assist you and solely to resolve the incident.</p>
<p>&nbsp;</p>
<p>10.1.4 Further to the above, you may receive telephone calls from an TruckWale representative and/or the relevant response team at the time of pressing the SOS button and in the duration that the incident is being resolved, and the same shall not be construed as a breach of TRAI guidelines, in as much as these would be made for Your security and safety purposes.</p>
<p>&nbsp;</p>
<p>10.2 Under this clause, You give Your express consent to permit TruckWale to undertake the above along with any ancillary actions that may be required to facilitate effective emergency response.</p>
<p>&nbsp;</p>
<p>10.3 TruckWale will not be liable for any deficiency of service, provided to You under this clause on a best efforts basis, and this clause does not, in any manner, restrain You from seeking any other form of assistance from any other party.</p>
<p>&nbsp;</p>
<ol start="11">
<li>FORCE MAJEURE</li>
</ol>
<p>&nbsp;</p>
<p>11.1 We shall not be liable for any failure to perform any obligations under this User Terms if the performance is prevented, hindered or delayed by a Force Majeure Event and in such case, our obligations under this User Terms shall be suspended for so long as the Force majeure Event continues.</p>
<p>&nbsp;</p>
<ol start="12">
<li>INDEMNIFICATION</li>
</ol>
<p>&nbsp;</p>
<p>12.1 By accepting these User Terms and using the Service, You agree that You shall defend, indemnify and hold TruckWale, its affiliates, their licensors, and each of its officers, directors, other users, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys' fees and costs) arising out of or in connection with: (a) Your violation or breach of any term of these User Terms or any Applicable Law or regulation, whether referenced herein; (b) Your violation of any rights of any third party, including the TPSPs \or (c) Your use or misuse of the Application or Service.</p>
<p>&nbsp;</p>
<ol start="13">
<li>LIABILITY</li>
</ol>
<p>&nbsp;</p>
<p>13.1. The information, recommendations and/or Services provided to you on or through the Site, the Application and TruckWale call centre are for general information purposes only and does not constitute advice. TruckWale will reasonably keep the Site and its contents correct and</p>
<p>&nbsp;</p>
<p>up to date but does not guarantee that (the contents of) the Site is free of errors, defects, malware and viruses or that the Site is correct, up to date and accurate.</p>
<p>&nbsp;</p>
<p>13.2. TruckWale shall not be liable for You missing trains/flights/events or delays etc. as the Service is dependent on many factors not in TruckWale&rsquo;s control. You must book Your Ride after taking into account the check-in time, traffic and weather conditions, political rallies, natural calamities, traffic barricades, car breakdowns and other unexpected delays.</p>
<p>&nbsp;</p>
<p>13.3. In the event, there is a delay by the Vehicle in reaching the pickup location beyond 30 (thirty) minutes of the pickup time, TruckWale shall only endeavour to get You in touch with the Driver assigned for Your Ride.</p>
<p>&nbsp;</p>
<p>13.4. TruckWale shall not be liable for any damages resulting from the use of or inability to use the Site, including damages caused by the wrong usage of the Site, error in call centre number, network issues, malware, viruses or any incorrectness or incompleteness of the Information or the or Application.</p>
<p>&nbsp;</p>
<p>13.5. You shall take full responsibility for your items and luggage. In case of lost items inside the vehicle during the journey, TruckWale will try to locate the items on a &ldquo;best-effort&rdquo; basis but is not responsible for the same in case of loss or damage to the same. If You leave any goods in the Vehicle or have any complaint in respect of the Services or the use of the Vehicle, You have to inform TruckWale of the same in writing within 24 (twenty-four) hours of using the Vehicle or the Services of TruckWale. In the event it is found, You shall be informed about the TruckWale office from where You can collect it after 3 (three) working days from the date You were informed. TruckWale however shall not be responsible for delivering the same back to You. If requested, TruckWale may deliver the misplaced item/s back to you after 3 (three) working days from the date You were informed, subject to the place of delivery being twenty (20) KMS from the TruckWale office. TruckWale shall charge you a flat fee of Rs 500 for such delivery.</p>
<p>&nbsp;</p>
<p>13.6. TruckWale does not assure a complete sustainability of its Service and shall not be held responsible or liable for the same, in any manner.</p>
<p>&nbsp;</p>
<p>13.7. TruckWale shall not be responsible for any loss of communication/information of status update and benefits under the program. All this information will be sent on the mobile number and/or email ID registered with TruckWale. TruckWale will not be responsible for the appropriateness of mobile or email or any other communication medium. You shall be responsible for immediately reporting the errors, if any, that occurred in the information sent to you regarding a booking confirmation.</p>
<p>&nbsp;</p>
<p>13.8. IN NO EVENT SHALL TruckWale BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES OR FOR ANY DAMAGES WHATSOEVER, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF TruckWale HAS BEEN ADVISED OF THE POSSIBILITY THEREOF.</p>
<p>&nbsp;</p>
<p>13.9. IN ADDITION, AND WITHOUT LIMITING THE FOREGOING, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL TruckWale&rsquo;s AGGREGATE LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE USER TERMS OR THE SERVICES RENDERED HEREUNDER, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE, PRODUCT LIABILITY, OR OTHER THEORY), WARRANTY, OR OTHERWISE, EXCEED THE AMOUNT OF Rs. 1000/- (Rupees One Thousand only).</p>
<p>&nbsp;</p>
<p>13.10. If Applicable Law does not permit the exclusion of certain warranties or the limitation or exclusion of liability, the scope and duration of such warranty exclusions and the extent of the liability of TruckWale shall be the minimum permitted under Applicable Law.</p>
<p>&nbsp;</p>
<ol start="14">
<li>APPLICATION LICENCE</li>
</ol>
<p>&nbsp;</p>
<p>14.1. Subject to Your compliance with these User Terms, TruckWale grants You a limited, revocable, non-exclusive, non-transferable and non-sublicensable licence to download and install a copy of the Application on a single mobile device that You own or control and to run such copy of the Application solely for Your own personal use and to use the Site.</p>
<p>&nbsp;</p>
<p>14.2. You shall not (i) license, sub-license, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Service or Site in any way; (ii) modify or make derivative works based upon the Service or Application; (iii) create Internet &ldquo;links&rdquo; to the Service or &ldquo;frame&rdquo; or &ldquo;mirror&rdquo; any Site on any other server or wireless or Internet-based device; (iv) reverse engineer or access the Site in order to (a) design or build a competitive product or service, (b) design or build a product using similar ideas, features, functions or graphics of the Service or Site, or (c) copy, reproduce, record, or make available to the public any ideas, features, functions or graphics of the Service or Site, or (v) launch an automated program or script, including, but not limited to, web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per second, or unduly burdens or hinders the operation and/or performance of the Service or Site.</p>
<p>&nbsp;</p>
<p>14.3. You shall not: (i) send spam or otherwise duplicative or unsolicited messages in violation of applicable laws; (ii) send or store infringing, obscene, threatening, libellous, or otherwise unlawful or tortious material, including material harmful to children or violative of third party privacy rights; (iii) send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs; (iv) interfere with or disrupt the integrity or performance of the Site, the Application or Service or the data contained therein; or (v) attempt to gain unauthorised access to the Site, the Application or Service or its related systems or networks.</p>
<p>&nbsp;</p>
<p>14.4. TruckWale will have the right to investigate and prosecute violations of the above to the fullest extent of the law. TruckWale may involve and cooperate with law enforcement authorities in prosecuting users who violate these User Terms. You acknowledge that TruckWale has no obligation to monitor Your access to or use of the Site, Service or Posted Content, but has the right to do so for the purpose of operating the Site and Service, to ensure Your compliance with these User Terms, or to comply with Applicable Law or the order or requirement of a court, administrative agency or other Governmental body. TruckWale reserves the right, at any time and without prior notice, to remove or disable access to any content that TruckWale, at its sole discretion, considers to be in violation of these User Terms or otherwise harmful to the Site, the Service or Application.</p>
<p>&nbsp;</p>
<ol start="15">
<li>CONTENT POSTED BY CUSTOMERS</li>
</ol>
<p>&nbsp;</p>
<p>15.1. TruckWale may accept the posting of any notes, messages, e-mails, photos, drawings, profiles, opinions, ideas, images, videos, audio files or other materials or information given by you on the Site (&ldquo;Posted Content&rdquo;) by You. You represent that you have obtained all permissions and consents required to post the Posted Content and such Posted Content complies with all requirements of the Posted Content. TruckWale shall not in any manner be responsible for or endorse the Posted Content.</p>
<p>&nbsp;</p>
<p>15.2. You agree that when posting Posted Content, You will not:</p>
<p>&nbsp;</p>
<p>(i) Publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, blasphemous, pornographic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful material or information.</p>
<p>&nbsp;</p>
<p>(ii) Upload files that contain software or other material protected by intellectual property laws (or by rights of privacy or publicity) unless you own or control the rights thereto or have received all necessary consents.</p>
<p>&nbsp;</p>
<p>(iii) Upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another&rsquo;s computer.</p>
<p>&nbsp;</p>
<p>(iv) Advertise or offer to sell or buy any goods or services for any business purpose, unless the Site specifically allows such messages.</p>
<p>&nbsp;</p>
<p>(v) Conduct or forward surveys, contests, pyramid schemes or chain letters.</p>
<p>&nbsp;</p>
<p>(vi) Download any file posted by another user that you know, or reasonably should know, cannot be legally distributed in such a manner.</p>
<p>&nbsp;</p>
<p>(vii) Falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded.</p>
<p>&nbsp;</p>
<p>(viii) Deceive or mislead the addressee about the origin of a message or communicate any information which is grossly offensive or menacing in nature.</p>
<p>&nbsp;</p>
<p>(ix) Restrict or inhibit any other user from using and enjoying the Site.</p>
<p>&nbsp;</p>
<p>(x) Violate any code of conduct or other guidelines which may be applicable for any particular Posted Content.</p>
<p>&nbsp;</p>
<p>(xi) Harvest or otherwise collect information about others, including e-mail addresses, without their consent.</p>
<p>&nbsp;</p>
<p>(xii) Threaten the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.</p>
<p>&nbsp;</p>
<p>(xiii) Violate any Applicable Laws or regulations including the Information Technology Act, 2000 and the rules, regulations and guidelines notified thereunder.</p>
<p>&nbsp;</p>
<ol start="16">
<li>INTELLECTUAL PROPERTY OWNERSHIP</li>
</ol>
<p>&nbsp;</p>
<p>16.1. TruckWale alone (and its licensors, where applicable) shall own all right, title and interest, including all related intellectual property rights, in and to (i) the Site, Application, Product, Service and any suggestions, ideas, enhancement requests, feedback, recommendations or any other offering; (ii) text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music, artwork and computer code; or (iii) other information provided by you or any other party relating to the Site, Application or the Service. Third-party trademarks may appear on this Site/ Application and all rights therein are reserved to the registered owners of those trademarks. For use of any third party's intellectual property, you need to get permission directly from the owner of the intellectual property for any use.</p>
<p>&nbsp;</p>
<p>16.2. These User Terms do not constitute a sale and do not convey to You any rights of ownership in or related to the Site, the Application or the Service, or any intellectual property rights owned by TruckWale. You shall be solely responsible for any violations of any laws and for any infringements of any intellectual property rights caused by use of the Services or the Site/ Application.</p>
<p>&nbsp;</p>
<p>16.3. You may use the information on the Site purposely made available by TruckWale for downloading from the Site, provided that You:</p>
<p>&nbsp;</p>
<p>(i) Do not remove any proprietary notice language in all copies of such documents and make no modifications to the information; (ii) use such information only for your personal, non-commercial, informational purpose and do not copy or post such information on any networked computer or broadcast it in any media; or (iii) do not make any additional representations or warranties relating to such information.</p>
<p>&nbsp;</p>
<ol start="17">
<li>LINKS</li>
</ol>
<p>&nbsp;</p>
<p>17.1. If permitted by TruckWale, You may establish a hypertext link to the Site, provided that the link does not state or imply any sponsorship or endorsement of Your site by Us. You must not use on Your site or in any other manner any TruckWale trademarks or service marks or any Content belonging to TruckWale and appearing on the Site, including any logos or characters, without our express written consent. You must not frame or otherwise incorporate into another third party website or present in conjunction with or juxtaposed against such a website any of the content or other materials on the Site without our prior written consent.</p>
<p>&nbsp;</p>
<ol start="18">
<li>TERM AND TERMINATION OF LICENCE AGREEMENT</li>
</ol>
<p>&nbsp;</p>
<p>18.1. Unless terminated in accordance with this Clause 17, the agreement between TruckWale and You is perpetual in nature upon downloading the Application and for each Ride booked through the Site.</p>
<p>&nbsp;</p>
<p>18.2. You are entitled to terminate the agreement at all times by deletion of Your Account, thus disabling the use by You of the Site. You can close Your Account at any time by following the instructions on the Site.</p>
<p>&nbsp;</p>
<p>18.3. TruckWale is entitled to terminate the agreement at all times and with immediate effect (by disabling Your use of the Site and the Service) if You: (a) violate or breach any term of these User Terms, or (b) in the opinion of TruckWale, misuse the Application or the Service. TruckWale is not obliged to give notice of the termination of the agreement in advance. After termination, TruckWale will give notice thereof in accordance with these User Terms.</p>
<p>&nbsp;</p>
<p>18.4. Termination of this agreement will not prejudice accrued rights of either TruckWale or You.</p>
<p>&nbsp;</p>
<p>18.5. Clauses 11 (Indemnification), 12 (Liability), 13 (Application Licence), 14 (Contents posted on Site/ Application), 15 (Intellectual Property Ownership), 17 (Term and Termination), 22 (Notice) and 24 (Applicable Law and Dispute Resolution) and such other provisions which are intended to survive the termination, shall survive the expiry/termination of these User Terms in accordance with their terms.</p>
<p>&nbsp;</p>
<ol start="19">
<li>INVALIDITY OF ONE OR MORE PROVISIONS</li>
</ol>
<p>&nbsp;</p>
<p>19.1. The invalidity of any term of these User Terms shall not affect the validity of the other provisions of these User Terms. If and to the extent that any provision of these User Terms is invalid, or is unacceptable in the given circumstances, a provision shall apply between the parties instead that is acceptable considering all the circumstances, taking into account the content and the purpose of these User Terms.</p>
<p>&nbsp;</p>
<ol start="20">
<li>CONFLICT In the event of any contradiction or inconsistency between this User Terms and any other agreement executed between You and TruckWale, the terms of the User Terms shall prevail unless the exception has been expressly agreed to in writing by making reference to the relevant Clause sought to be modified under this User Terms.</li>
</ol>
<p>&nbsp;</p>
<ol start="21">
<li>DISCLAIMER</li>
</ol>
<p>&nbsp;</p>
<p>21.1. You agree that TruckWale is merely an electronic platform to facilitate aggregation of Vehicles and does not in any manner provide transportation services. TruckWale does not endorse, advertise, advise or recommend you to avail the Services of any Driver. TruckWale also does not guarantee or provide assurance in respect of the behaviour, actions or data of the users posted on the Site.</p>
<p>&nbsp;</p>
<p>21.2. We do not authorise anyone to make a warranty on our behalf, and You shall not rely on any statement of warranty as a warranty by Us.</p>
<p>&nbsp;</p>
<p>21.3. TruckWale and their representatives, officers, employees, agents and contractors shall not be liable for any loss, damage, claim, expense, cost (including legal costs) or liability arising directly or indirectly from Your use or non-use of the Service or the Site, or Your reliance upon the Service or the information contained upon the Site (whether arising from TruckWale or any other person's negligence or otherwise).</p>
<p>&nbsp;</p>
<p>21.4. This Site, Application and all content on the Site and the Application are provided on an &ldquo;as is&rdquo; basis without warranties of any kind, either express or implied, including without limitation warranties of title or implied warranties of merchantability or fitness for a particular purpose. You acknowledge, by Your access of the Site and/or Application, that Your access of the Site and/or Application and availing of Services is at Your sole risk, that You assume full responsibility for Your access and use of the Site and/or Application, and that TruckWale shall not be liable for any damages of any kind related to Your access and use of this Site and/or Application.</p>
<p>&nbsp;</p>
<p>21.5. All images, audio, video and text in the Site and/or Application are only for illustrative purposes. None of the models, actors or products in the images, if any, are endorsing the Services in any manner. Any resemblance of any matter to anybody or anything is purely unintentional and/or coincidental.</p>
<p>&nbsp;</p>
<p>21.6. TruckWale is not engaged in the insurance business and does not provide any insurance services. TruckWale has facilitated the provision of insurance services for the benefit of customers, under group travel insurance policies availed from insurance companies, whereby TruckWale is acting as the group manager of the policy. TruckWale does not guarantee or make any promise in relation to the insurance policy/ insurance company, including but not limited to any benefits from the use of the insurance services provided by the insurance companies, such as coverage, claims and settlements. Any claim or servicing of insurance policies, raised through the Application, remains a matter between the Customer and the insurance company, and TruckWale shall not be responsible for the actions of the insurance company or the Customer. It is to be noted that the insurance policy number, claim certificate, invoice for the insurance premium/ fee collected from the Customer is not be issued by TruckWale but will be issued by the respective insurance company. Any issues in receiving tax invoices or issues faced in claiming the insurance are not the responsibility of TruckWale. TruckWale disclaims all in all liability in relation to the services of the insurance company. Please reach out to the insurance company in case of any questions/ issues.</p>
<p>&nbsp;</p>
<ol start="22">
<li>MODIFICATION OF THE SERVICE AND USER TERMS</li>
</ol>
<p>&nbsp;</p>
<p>22.1. TruckWale reserves the right, at its sole discretion, to modify or replace, in part or full, any of these User Terms, or change, suspend, block, discontinue or restrict your use to all or any feature of the Service or Application at any time.</p>
<p>&nbsp;</p>
<p>22.2. TruckWale shall not be required to notify you of any changes made to these User Terms. The revised User Terms shall be made available on the Site. You are requested to regularly visit the Site to view the most current User Terms. You can determine when TruckWale last modified the User Terms by referring to the &ldquo;Last Updated&rdquo; legend above. It shall be your responsibility to check these User Terms periodically for changes. TruckWale may require you to provide Your consent to the updated User Terms in a specified manner prior to any further use of the Site and the Services. If no such separate consent is sought, Your continued use of the Site, following the changes to the User Terms, will constitute Your acceptance of those changes. Your use of the Site and the Services is subject to the most current version of the User Terms made available on the Site at the time of such use.</p>
<p>&nbsp;</p>
<ol start="23">
<li>NOTICE</li>
</ol>
<p>&nbsp;</p>
<p>23.1. TruckWale may give notice by means of a general notice on the Service or Application, or by electronic mail to Your email address or a message on Your registered mobile number, or by written communication sent by regular mail to Your address on record in TruckWale&rsquo;s account information.</p>
<p>&nbsp;</p>
<p>23.2. You may contact TruckWale by electronic mail at our email address or by written communication sent by regular mail to our address at</p>
<p>&nbsp;</p>
<p>24.1. You shall not assign Your rights under these User Terms without the prior written approval of TruckWale. TruckWale can assign its rights under the User Terms to any affiliate.</p>
<p>&nbsp;</p>
<ol start="25">
<li>APPLICABLE LAW AND DISPUTE RESOLUTION</li>
</ol>
<p>&nbsp;</p>
</body>
</html>